[package]
name = "qanglang-core"
version = "0.1.0"
edition = "2024"

[features]
profiler = ["coz"]

[dependencies]
phf = { workspace = true }
generational-arena = "0.2.9"

[target.'cfg(unix)'.dependencies]
coz = { workspace = true, optional = true }