[package]
name = "qanglang-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "qang"
path = "src/main.rs"

[dependencies]
qanglang-core = { path = "../qanglang-core" }
qanglang-ls = { path = "../qanglang-ls" }
qanglang-test = { path = "../qanglang-test" }
clap = {version = "4.5.43", features = ["derive"]}
