# Sample workflow for building and deploying an Astro site to GitHub Pages
#
# To get started with Astro see: https://docs.astro.build/en/getting-started/
#
name: Deploy Astro site to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Show debug info (temporary)
        run: |
          which npm || true
          which pnpm || true
          which yarn || true
          node --version || true
          echo $PATH
          ls -la docs

      - name: Install dependencies
        working-directory: ./docs
        run: npm ci

      - name: Build site
        working-directory: ./docs
        run: npm run build --if-present

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        # If your build output is the docs folder itself (static), set path: ./docs
        # If your build outputs to docs/dist or docs/build, change path accordingly
        with:
          path: ./docs/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
